plot(c(1,3) ,c(3,10))
plot(1:10 , type="l")
x <- c(1,2)
y <- c ( 4,8)
plot(x,y ,main= " My graph",xlab="x -axis",ylab="y-axis",col="red",type="l",lwd=4)
plot(2:100,col="cyan",cex=10)
x <- c (1,2,3,4,10,20,40,50)
# y <- c("a","b","c","d","e",'f',"g","f")
pie(x)
barplot(x,y,names.arg = x ,col="yellow")
barplot(x,y,names.arg = x ,col="yellow",horizontal=TRUE)
